"""Detector fine-tuning + the run registry.

PRD 9.1 and 9.7. Two things this module is responsible for beyond calling
Ultralytics:

1. **`data.yaml` is generated, never hand-maintained.** It is derived from the
   manifest that the leakage test guards, so the file the trainer reads and the
   file CI validates cannot drift apart. A hand-edited `data.yaml` pointing at
   a stale split directory is how a "fixed" leak quietly comes back.

2. **Every run writes `runs/<run_id>/run.json`** with the resolved config, the
   git SHA, the dataset hash, library versions and hardware -- so any number in
   any report traces back to the exact run that produced it (9.7).

Model selection is by **val mAP@0.5:0.95**, never by training loss, and the
test split is touched exactly once, at the end (9.1).
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from ..config import Config
from ..data.manifest import read_manifest
from ..data.sampler import dataset_hash
from ..data.splitter import assert_no_leakage
from ..eval.report import git_sha
from ..utils.device import environment_report, resolve_device, seed_everything
from ..utils.logging import get_logger

log = get_logger("models.train")


def write_data_yaml(cfg: Config, path: Path | None = None) -> Path:
    """Emit the Ultralytics dataset descriptor from the current splits."""
    splits_dir = cfg.path("splits_dir")
    out = path or (cfg.root / "configs" / "data_generated.yaml")
    payload = {
        "path": str(splits_dir.as_posix()),
        "train": "train/images",
        "val": "val/images",
        "test": "test/images",
        "names": {i: n for i, n in enumerate(cfg.dataset.classes)},
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# GENERATED by src/models/train.py -- do not edit.\n"
        "# Derived from data/manifest.csv, which tests/test_no_leakage.py guards.\n"
        + yaml.safe_dump(payload, sort_keys=False),
        encoding="utf-8",
    )
    return out


@dataclass
class TrainArgs:
    """PRD 9.1 starting point, tuned by EXP-1/EXP-7. Overridable from the CLI."""

    model: str = "yolo11n.pt"
    epochs: int = 60
    patience: int = 20
    batch: int = 8
    imgsz: int = 640
    optimizer: str = "AdamW"
    lr0: float = 0.001
    lrf: float = 0.01
    cos_lr: bool = True
    warmup_epochs: float = 3.0
    weight_decay: float = 0.0005
    momentum: float = 0.937
    box: float = 7.5
    cls: float = 0.5
    dfl: float = 1.5
    hsv_h: float = 0.015
    hsv_s: float = 0.7
    hsv_v: float = 0.4
    degrees: float = 0.0
    translate: float = 0.1
    scale: float = 0.5
    fliplr: float = 0.5
    flipud: float = 0.0        # deliberate: traffic scenes have a gravity prior
    mosaic: float = 1.0
    close_mosaic: int = 10     # mosaic distorts box statistics near convergence
    mixup: float = 0.1
    amp: bool = True
    freeze: int | None = None  # EXP-7: freeze-backbone vs full fine-tune
    workers: int = 4

    def to_ultralytics(self) -> dict[str, Any]:
        d = {k: v for k, v in asdict(self).items() if v is not None}
        d.pop("model")
        return d


@dataclass
class RunRecord:
    run_id: str
    started: str
    finished: str = ""
    args: dict[str, Any] = field(default_factory=dict)
    env: dict[str, Any] = field(default_factory=dict)
    git_sha: str = ""
    config_fingerprint: str = ""
    dataset_hash: str = ""
    device: str = ""
    duration_s: float = 0.0
    best_weights: str = ""
    metrics: dict[str, Any] = field(default_factory=dict)

    def save(self, directory: Path) -> Path:
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / "run.json"
        path.write_text(json.dumps(asdict(self), indent=2, default=str), encoding="utf-8")
        return path


def train_detector(
    cfg: Config,
    args: TrainArgs | None = None,
    run_name: str | None = None,
    resume: bool = False,
) -> RunRecord:
    """Fine-tune a YOLO detector and register the run."""
    from ultralytics import YOLO

    args = args or TrainArgs()
    seed_everything(cfg.seed)

    rows = read_manifest(cfg.path("manifest"))
    # The leak guard runs here too, not only in CI: the cost of catching it now
    # is one second; the cost of catching it later is every number produced
    # since (PRD R3).
    assert_no_leakage(rows)

    for split in ("train", "val"):
        images = cfg.path("splits_dir") / split / "images"
        if not images.exists() or not any(images.iterdir()):
            raise FileNotFoundError(
                f"{images} is empty -- run `python -m src.cli split --copy` first"
            )

    data_yaml = write_data_yaml(cfg)
    device = resolve_device(cfg.detection.device)
    run_id = run_name or f"{Path(args.model).stem}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    run_dir = cfg.path("runs_dir") / run_id

    record = RunRecord(
        run_id=run_id,
        started=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        args=asdict(args),
        env=environment_report(),
        git_sha=git_sha(cfg.root),
        config_fingerprint=cfg.fingerprint(),
        dataset_hash=dataset_hash(rows),
        device=device.device,
    )
    record.save(run_dir)

    ul_args = args.to_ultralytics()
    if not device.is_gpu:
        # AMP is a CUDA feature; leaving it on for a CPU run wastes time in a
        # no-op autocast and, on some versions, triggers a GPU-only check.
        ul_args["amp"] = False
        log.warning(
            "training on CPU: AMP disabled. PRD R9 mitigation -- run the real "
            "training on Colab/Kaggle and pull best.pt back into runs/.",
            extra={"event": "cpu_training"},
        )

    log.info(
        f"training {args.model} for {args.epochs} epochs on {device.device} -> {run_dir}",
        extra={"event": "train_start", "run_id": run_id, "model": args.model},
    )
    t0 = time.perf_counter()
    model = YOLO(args.model)
    results = model.train(
        data=str(data_yaml),
        project=str(cfg.path("runs_dir")),
        name=run_id,
        exist_ok=True,
        seed=cfg.seed,
        device=device.device,
        resume=resume,
        plots=True,
        **ul_args,
    )
    record.duration_s = round(time.perf_counter() - t0, 2)
    record.finished = datetime.now(timezone.utc).isoformat(timespec="seconds")

    best = run_dir / "weights" / "best.pt"
    record.best_weights = str(best) if best.exists() else ""
    try:
        rd = getattr(results, "results_dict", {}) or {}
        record.metrics = {str(k): float(v) for k, v in rd.items() if isinstance(v, (int, float))}
    except Exception:
        record.metrics = {}
    record.save(run_dir)

    log.info(
        f"training finished in {record.duration_s:.1f}s; best -> {record.best_weights or 'n/a'}",
        extra={"event": "train_done", "run_id": run_id, **record.metrics},
    )
    return record


def list_runs(cfg: Config) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    runs_dir = cfg.path("runs_dir")
    if not runs_dir.exists():
        return out
    for path in sorted(runs_dir.glob("*/run.json")):
        try:
            out.append(json.loads(path.read_text(encoding="utf-8")))
        except json.JSONDecodeError:
            continue
    return out
